services:
  python:
    command: poetry run uvicorn main:app --host 0.0.0.0 --reload
    build: .
    volumes:
      - .:/workdir
    env_file:
      - .env
    ports:
      - 8000:8000
    tty: true
    stdin_open: true
